### ISSUE TITLE
Firefox Extension

### ISSUE THREAD

**Issue by FerroEduardo** [israNascimento/SIGAA-RURAL#4]
Seria possível publicar a extensão para o Firefox também? Instalei a extensão nele e funcionou perfeitamente sem nenhuma alteração no código.

**Comment by israNascimento** [comment]
Posso ver no final de semana, se for de graça ou baratinho coloco sim, lembro que no chrome paguei acho que 20 dol pra colocar na loja. Se vc quiser, pode colocar lá também sem caô, feel free.

**Comment by FerroEduardo** [comment]
Consegui publicar gratuitamente e estará disponível [aqui](https://addons.mozilla.org/en-US/firefox/addon/sigaa-rural/) quando o review for finalizado. Também coloquei dos créditos e peguei algumas coisas lá da [Chrome Web Store](https://chrome.google.com/webstore/detail/sigaa-rural/oincadmpbogdfgckicmpclkdmcfagajg?hl=pt-BR).

**Comment by FerroEduardo** [comment]
Foi aprovado
